name: jasmine
description: jasmine comic browser

publish_to: 'none'

version: 1.2.13+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  permission_handler: ^8.3.0
  flutter_styled_toast: ^2.0.0
  photo_view: ^0.13.0
  event: ^2.0.5
  modal_bottom_sheet: ^2.0.0
  another_xlider: ^1.0.1+2
  scrollable_positioned_list: ^0.2.3
  url_launcher: ^6.0.17
  clipboard: ^0.1.3
  file_picker: ^4.6.1
  filesystem_picker: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
